---
- name: Collect javac Version
  
  gather_facts: yes

  tasks:
    - name: Collect javac Version
      command: javac -version
      register: javac_version_result
      ignore_errors: yes

    - name: Display javac Version
      debug:
        var: javac_version_result.stdout_lines
