- name: Execute
  hosts: all
  tasks:
    - name: Execute against dev
      shell: 'echo "dev"'
      register: cmd_dev_out
    - set_fact:
      with_items: "{{ cmd_dev_out.stdout_lines }}"
      no_log: true