---
# This playbook runs a basic python command.

- hosts: all

  tasks:
  - name: Find Python Version
    command: python --version
    register: ps
  - local_action: command echo item
    with_items: ps.stdout_lines
