- name: Transfer and execute a script.
  hosts: all
  become_user: root
  vars:
     ansible_python_interpreter: /usr/bin/python3
     #  fix_mode: false # Set this to true in job template extra vars
  tasks:
  - script: date.sh
    register: results
  - debug:
      var: results.stdout